name = "cd-comment"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "comments"
database_id = "8d6d7acf-1953-4f45-af3f-26c09e49c46f"    # Will be set during deployment

[vars]
DEFAULT_TURNSTILE_SITE_KEY = "0x4AAAAAACY8KMf3oN7ZC-bs"
ADMIN_PASSWORD = "1234"   #your passwords
